
variable "boot_wait" {
  type    = string
  default = "5s"
}

variable "box_name" {
  type    = string
  default = "RL87_Dev"
}

variable "disk_size" {
  type    = string
  default = "40960"
}

variable "iso_checksum" {
  type    = string
  default = "4827dce1c58560d3ca470a5053e8d86ba059cbb77cfca3b5f6a5863d2aac5b84"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_name" {
  type    = string
  default = "Rocky-8.7-x86_64-dvd1.iso"
}

variable "memsize" {
  type    = string
  default = "2048"
}

variable "numvcpus" {
  type    = string
  default = "2"
}

variable "ssh_password" {
  type    = string
  default = "vagrant"
}

variable "ssh_username" {
  type    = string
  default = "vagrant"
}

variable "vm_name" {
  type    = string
  default = "RL87_Dev"
}

source "qemu" "autogenerated_1" {
  accelerator      = "kvm"
  boot_command     = ["<tab> text inst.ks=http://192.168.1.6:{{ .HTTPPort }}/rocky/ks8_4_dvd.cfg<enter><wait>"]
  boot_wait        = "${var.boot_wait}"
  disk_size        = "${var.disk_size}"
  format           = "qcow2"
  http_directory   = "http"
  iso_checksum     = "${var.iso_checksum}"
  iso_urls         = ["./iso/${var.iso_name}"]
  shutdown_command = "echo '${var.ssh_password}'|sudo -S /sbin/halt -h -p"
  ssh_password     = "${var.ssh_password}"
  ssh_username     = "${var.ssh_username}"
  ssh_wait_timeout = "10500s"
}

source "virtualbox-iso" "virtualbox" {
  boot_command            = ["<tab> text inst.ks=http://192.168.1.6:{{ .HTTPPort }}/rocky/ks8_4_dvd.cfg<enter><wait>"]
  boot_wait               = "${var.boot_wait}"
  disk_size               = "${var.disk_size}"
  guest_os_type           = "RedHat_64"
  headless                = false
  http_directory          = "./http"
  iso_checksum            = "${var.iso_checksum}"
  iso_interface           = "sata"
  iso_urls                = ["./iso/${var.iso_name}"]
  shutdown_command        = "echo '${var.ssh_password}'|sudo -S /sbin/halt -h -p"
  ssh_password            = "${var.ssh_password}"
  ssh_port                = 22
  ssh_timeout             = "10500s"
  ssh_username            = "${var.ssh_username}"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "${var.memsize}"], ["modifyvm", "{{ .Name }}", "--cpus", "${var.numvcpus}"], ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"], ["modifyvm", "{{ .Name }}", "--vram", "16"]]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "${var.vm_name}"
}

source "vmware-iso" "vmware" {
  boot_command     = ["<tab> text inst.ks=http://192.168.1.6:{{ .HTTPPort }}/rocky/ks8_4_dvd.cfg<enter><wait>"]
  boot_wait        = "${var.boot_wait}"
  disk_size        = "${var.disk_size}"
  disk_type_id     = "0"
  guest_os_type    = "centos-64"
  headless         = false
  http_directory   = "http"
  iso_checksum     = "${var.iso_checksum}"
  iso_urls         = ["./iso/${var.iso_name}"]
  shutdown_command = "echo '${var.ssh_password}'|sudo -S /sbin/halt -h -p"
  ssh_password     = "${var.ssh_password}"
  ssh_port         = 22
  ssh_timeout      = "10500s"
  ssh_username     = "${var.ssh_username}"
  vm_name          = "${var.vm_name}"
}

build {
  sources = ["source.qemu.autogenerated_1", "source.virtualbox-iso.virtualbox", "source.vmware-iso.vmware"]

  provisioner "file" {
    destination = "/tmp/devtools.sh"
    source      = "scripts/bash/dev_tools.sh"
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_password}'|{{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["scripts/bash/vagrant.sh", "scripts/bash/rocky/update.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_password}'|{{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["scripts/bash/cleanup.sh", "scripts/bash/zerodisk.sh"]
  }

  post-processor "vagrant" {
    keep_input_artifact = true
    only                = ["virtualbox-iso.virtualbox"]
    output              = "builds/${var.box_name}-virtualbox.box"
  }
}
